# Generated by Django 4.2.5 on 2023-10-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arts',
            options={'verbose_name': 'Картина', 'verbose_name_plural': 'Картины'},
        ),
        migrations.AlterField(
            model_name='arts',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='arts',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Цена'),
        ),
    ]
